name = "new_cloud_flare"
main = "src/worker.ts"
compatibility_date = "2023-05-15"

account_id = "e5e239f98067fdddb46e62b16e35026b"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["* * * * *"] # * * * * * = run every minute

[vars]
REALM_APPID = "application-0-vxdkp"
